add_executable(mira_dns_message_tests test_message.cpp)
target_link_libraries(mira_dns_message_tests PRIVATE Mira::dns Mira::warnings)
add_executable(mira_dns_doh_tests test_doh.cpp)
target_link_libraries(mira_dns_doh_tests PRIVATE Mira::dns Mira::transport Mira::warnings)
add_executable(mira_dns_doh_allocation_tests test_doh_allocation.cpp)
target_link_libraries(mira_dns_doh_allocation_tests PRIVATE Mira::dns Mira::warnings)
foreach(target mira_dns_message_tests mira_dns_doh_tests mira_dns_doh_allocation_tests)
    target_include_directories(${target} PRIVATE ${PROJECT_SOURCE_DIR}/modules/core/tests)
endforeach()
add_test(NAME dns.message COMMAND mira_dns_message_tests)
add_test(NAME dns.doh COMMAND mira_dns_doh_tests)
add_test(NAME dns.doh_allocation COMMAND mira_dns_doh_allocation_tests)
set_tests_properties(dns.message dns.doh dns.doh_allocation PROPERTIES TIMEOUT 60)

add_executable(mira_dns_query_tests test_query.cpp)
target_link_libraries(mira_dns_query_tests PRIVATE Mira::dns Mira::transport Mira::warnings)
target_include_directories(mira_dns_query_tests PRIVATE ${PROJECT_SOURCE_DIR}/modules/core/tests)
add_test(NAME dns.query COMMAND mira_dns_query_tests)
set_tests_properties(dns.query PROPERTIES TIMEOUT 60)
